name: auto-label pull request

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  label_pull_request:
    name: label pull request
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/label-pull-request.yml
