name: call flush caches

on:
  # Allow manually running this workflow.
  workflow_dispatch:

jobs:
  flush_caches:
    name: flush caches
    permissions:
      actions: write
    uses: ./.github/workflows/flush-caches.yml
