name: check shell

on:
  workflow_call:

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Check formatting
        uses: luizm/action-sh-checker@883217215b11c1fabbf00eb1a9a041f62d74c744
        env:
          SHFMT_OPTS: --simplify
        with:
          sh_checker_shellcheck_disable: true

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Check lints
        uses: luizm/action-sh-checker@883217215b11c1fabbf00eb1a9a041f62d74c744
        with:
          sh_checker_shfmt_disable: true
