name: check rust / beta

on:
  workflow_call:

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings

jobs:
  test_beta:
    name: test beta
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Install beta Rust toolchain
        uses: dtolnay/rust-toolchain@7e38f4b43b4db5c8dd498af069a4f6196df1d067
        with:
          toolchain: beta

      - name: Set override to beta Rust
        run: rustup override set beta

      - name: Install cargo-nextest
        uses: taiki-e/install-action@83ac0ad63c0167e6f06796fab0fce28db1bf3db0
        with:
          tool: cargo-nextest

      - name: Compile tests
        run: cargo test --locked --no-run

      - name: Run tests
        run: cargo nextest run --locked --all-targets

      - name: Run doctests
        run: cargo test --locked --doc
