name: deploy github pages / zig

on:
  workflow_call:

jobs:
  build_docs:
    name: build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - uses: korandoru/setup-zig@3d137e800ac114393177819328e565c3adc75210
        with:
          zig-version: master

      - name: Build docs
        run: zig test -femit-docs src/main.zig

      - name: Upload github-pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: docs

  deploy_docs_artifact:
    name: deploy docs artifact
    permissions:
      actions: read
      id-token: write
      pages: write
    needs: build_docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
