name: deploy github pages / rust

on:
  workflow_call:

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings

jobs:
  build_docs:
    name: build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Install nightly Rust toolchain
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: nightly

      - name: Build docs
        env:
          RUSTDOCFLAGS: --enable-index-page -Z unstable-options
        run: cargo +nightly doc --no-deps

      # prevent deployment_perms_error due to file permissions
      - name: Remove lock file
        run: rm target/doc/.lock

      - name: Upload github-pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: target/doc

  deploy_docs_artifact:
    name: deploy docs artifact
    permissions:
      actions: read
      id-token: write
      pages: write
    needs: build_docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
