name: flush caches

on:
  workflow_call:

jobs:
  delete_cache_entries:
    name: delete cache entries
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - name: Delete all GitHub Actions cache entries for the current branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          gh extension install actions/gh-actions-cache
          REPO="${{ github.repository }}"
          BRANCH="${{ github.ref }}"
          cache_keys=$(gh actions-cache list -R "$REPO" -B "$BRANCH" | cut -f 1)
          set +e
          for key in $cache_keys; do
            gh actions-cache delete "$key" -R "$REPO" -B "$BRANCH" --confirm
          done
