name: github actions

"on":
  workflow_call:

jobs:
  lint_workflows:
    name: lint workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Lint GitHub Actions workflow files
        uses: raven-actions/actionlint@d6c9e3222b489401880e866bc6715049773b63a3
        with:
          group-result: false
