name: labeler

on:
  workflow_call:

jobs:
  label_pr:
    name: label pull request
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Label pull request based on paths of changed files
        uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594
        with:
          dot: true
