name: label pull request

on:
  workflow_call:

jobs:
  check_labeler_matches:
    name: check labeler matches
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Label pull request based on paths of changed files
        uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213
        with:
          dot: true
