name: label pull request

on:
  workflow_call:

jobs:
  check_labeler_matches:
    name: check labeler matches
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Label pull request based on paths of changed files
        uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d
        with:
          dot: true
