name: push to main

"on":
  push:
    branches:
      - main

  # Allow manually running this workflow.
  workflow_dispatch:

jobs:
  cache_actionlint:
    name: cache actionlint
    uses: ./.github/workflows/preload-cache-actionlint.yml
