name: push to main

"on":
  push:
    branches:
      - main

  # Allow manually running this workflow.
  workflow_dispatch:

jobs:
  detect_changed_files:
    name: detect changed files
    permissions:
      pull-requests: read
    uses: ./.github/workflows/detect-changed-files.yml
