name: pull request

"on":
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  detect_changed_files:
    name: detect changed files
    permissions:
      pull-requests: read
    uses: ./.github/workflows/detect-changed-files.yml

  github_actions:
    name: github actions
    needs: detect_changed_files
    if: needs.detect_changed_files.outputs.github_actions == 'true'
    uses: ./.github/workflows/github-actions.yml

  markdown:
    name: markdown
    needs: detect_changed_files
    if: needs.detect_changed_files.outputs.markdown == 'true'
    uses: ./.github/workflows/markdown.yml
    with:
      files: ${{ needs.detect_changed_files.outputs.markdown_files }}
      prettier_version: "3.0.0"

  spelling:
    name: spelling
    needs: detect_changed_files
    if: needs.detect_changed_files.outputs.added_or_modified == 'true'
    uses: ./.github/workflows/spelling.yml
    with:
      files: ${{ needs.detect_changed_files.outputs.added_or_modified_files }}

  ready_to_merge:
    name: ready to merge
    needs:
      - detect_changed_files
      - github_actions
      - markdown
      - spelling
    if: always()
    uses: ./.github/workflows/ready-to-merge.yml
    with:
      needs_context: ${{ toJson(needs) }}
