name: schedule weekly

"on":
  schedule:
    # Run every Monday at 7:45am UTC.
    - cron: 45 7 * * 1

  # Allow manually running this workflow.
  workflow_dispatch:

jobs:
  flush_cache:
    name: flush cache
    permissions:
      actions: write
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/flush-cache.yml

  cache_actionlint:
    name: cache actionlint
    needs: flush_cache
    uses: ./.github/workflows/preload-cache-actionlint.yml
