name: schedule weekly

"on":
  schedule:
    # Run every Monday at 7:45am UTC.
    - cron: 45 7 * * 1

jobs:
  cache_actionlint:
    name: cache actionlint
    uses: ./.github/workflows/preload-cache-actionlint.yml
