name: preload caches / actionlint

on:
  workflow_call:

jobs:
  cache_actionlint_latest:
    name: cache actionlint / latest
    runs-on: ubuntu-latest
    steps:
      - name: Save latest actionlint into GitHub Actions cache
        uses: raven-actions/actionlint@205b530c5d9fa8f44ae9ed59f341a0db994aa6f8
        with:
          group-result: false
          flags: -version
