name: publish crate

on:
  workflow_call:

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings

jobs:
  publish_unpublished:
    name: publish unpublished
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@67ef31d5b988238dd797d409d6f9574278e20537
        with:
          toolchain: stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4
        with:
          shared-key: stable-ubuntu-latest
        timeout-minutes: 5

      - id: crates_io_auth
        name: Authenticate with crates.io
        uses: rust-lang/crates-io-auth-action@c6f97d42243bad5fab37ca0427f495c86d5b1a18

      - name: Publish crate to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.crates_io_auth.outputs.token }}
        run: cargo publish

      - name: Annotate workflow run with published crate URL
        run: |
          echo "### :shipit: Published crate for ${GITHUB_REF_NAME}:" >>"$GITHUB_STEP_SUMMARY"
          echo "- https://crates.io/crates/${GITHUB_REF_NAME%-v*}/${GITHUB_REF_NAME#*-v}/" >>"$GITHUB_STEP_SUMMARY"
