name: pull request

"on":
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

permissions:
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  detect_changed_files:
    name: detect changed files
    uses: ./.github/workflows/detect-changed-files.yml

  github_actions:
    name: github actions
    needs: detect_changed_files
    uses: ./.github/workflows/github-actions.yml

  markdown:
    name: markdown
    needs: detect_changed_files
    uses: ./.github/workflows/markdown.yml

  spelling:
    name: spelling
    needs: detect_changed_files
    uses: ./.github/workflows/spelling.yml

  ready_to_merge:
    name: ready to merge
    needs:
      - detect_changed_files
      - github_actions
      - markdown
      - spelling
    if: always()
    uses: ./.github/workflows/ready-to-merge.yml
    with:
      needs_context: "${{ toJson(needs) }}"
