name: pull request target

"on":
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  labeler:
    name: labeler
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/labeler.yml
