name: spelling

"on":
  workflow_call:
    inputs:
      files:
        type: string
        default: "."

jobs:
  check_for_typos:
    name: check for typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Check files for common misspellings
        # NOTE: dependabot struggles with determining the latest release version
        #       in this monorepo; see https://github.com/crate-ci/typos/releases
        uses: crate-ci/typos@27c9fe7c7948486ff5013a8a5a5c7f0587323f18
        with:
          files: "${{ inputs.files }}"
