name: tag if missing

on:
  workflow_call:
    inputs:
      toolbox_envy_bins:
        description: Toolbox Envy bin namespaces
        required: true
        type: string
    secrets:
      APP_ID:
        description: GitHub App installation ID
        required: true
      APP_PRIVATE_KEY:
        description: GitHub App private key
        required: true

jobs:
  tag_if_missing:
    name: ensure tag exists
    runs-on: ubuntu-latest
    steps:
      - id: generate_token
        name: Generate a GitHub App token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write

      - name: Checkout source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: Configure Git identity
        run: |
          git config user.name "senile-errata[bot]"
          git config user.email "senile-errata@users.noreply.github.com"

      - name: Add Toolbox Envy to PATH
        uses: EarthmanMuons/toolbox-envy/.github/actions/add-to-path@main
        with:
          include_bins: ${{ inputs.toolbox_envy_bins }}

      - id: tag
        name: Add any missing tags
        run: |
          set -euo pipefail
          tag="$(get-project-version | tag-if-missing)"
          echo "tag=$tag" >>"$GITHUB_OUTPUT"

      - name: Annotate workflow run with tag result
        env:
          STEPS_TAG_OUTPUTS_TAG: ${{ steps.tag.outputs.tag }}
        run: |
          set -euo pipefail

          if [[ -n "${STEPS_TAG_OUTPUTS_TAG}" ]]; then
            echo "::notice::Created missing tag ${STEPS_TAG_OUTPUTS_TAG}."
            {
              echo "### :sparkles: New tags:"
              echo
              echo "- \`${STEPS_TAG_OUTPUTS_TAG}\`"
            } >>"$GITHUB_STEP_SUMMARY"
          else
            echo "::notice::No missing tags were found."
          fi
