name: wordsmith

"on":
  workflow_call:

env:
  PRETTIER_VERSION: 3.0.0

jobs:
  changed_files:
    name: detect changed files
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      markdown: ${{ steps.filter.outputs.markdown }}
      markdown_files: ${{ steps.filter.outputs.markdown_files }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          fetch-depth: 20
      - name: Filter changed repository files
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        id: filter
        with:
          list-files: shell
          filters: |
            markdown:
              - added|modified: '**/*.md'

  check_markdown:
    name: check markdown
    needs:
      - changed_files
    runs-on: ubuntu-latest
    if: needs.changed_files.outputs.markdown == 'true'
    steps:
      - name: Checkout source code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Check Markdown formatting
        run: npx --yes "prettier@${{ env.PRETTIER_VERSION }}" --check --debug-check --color --prose-wrap always -- ${{ needs.changed_files.outputs.markdown_files }}

  check_spelling:
    name: check spelling
    needs:
      - changed_files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Check common misspellings
        uses: crate-ci/typos@ccdede0f8c1e877aa3248b9c837f3f9b0abbbdf9

  workflow_ready:
    name: workflow ready
    needs:
      - changed_files
      - check_markdown
      - check_spelling
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: "Check status of job_id: changed_files"
        run: |-
          RESULT="${{ needs.changed_files.result }}";
          if [[ $RESULT == "success" || $RESULT == "skipped" ]]; then
              exit 0
          else
              echo "***"
              echo "Error: The required job did not pass."
              exit 1
          fi
      - name: "Check status of job_id: check_markdown"
        run: |-
          RESULT="${{ needs.check_markdown.result }}";
          if [[ $RESULT == "success" || $RESULT == "skipped" ]]; then
              exit 0
          else
              echo "***"
              echo "Error: The required job did not pass."
              exit 1
          fi
      - name: "Check status of job_id: check_spelling"
        run: |-
          RESULT="${{ needs.check_spelling.result }}";
          if [[ $RESULT == "success" || $RESULT == "skipped" ]]; then
              exit 0
          else
              echo "***"
              echo "Error: The required job did not pass."
              exit 1
          fi
